name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  # PERSONAL_TOKEN_MUHAI_BOT, workflow
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: yarn install

      - name: Types Generate
        run: yarn job

      - name: Build App
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Push SubModules
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ci-tuya-components-styled-docs
          repo: tuya/tuya-panel-kit-docs
          token: ${{ secrets.PERSONAL_TOKEN_MUHAI_BOT }}
